package com.web.myproject;

import java.util.ArrayList;
import java.util.List;

import com.web.myproject.Atributos;

public class AtributosBase {
	
	Atributos at = new Atributos();
	
/*	public Atributos añadirAtributos(){
		at.setIdAtributo(1);
		at.setNombre("abbr");
		at.setTipoAtributo("abreviatura de celda de cabecera");
		at.setIdAtributo(2);
		at.setNombre("accept-charset");
		at.setTipoAtributo("abreviatura de celda de cabecera");
		at.setIdAtributo(3);
		at.setNombre("accept");
		at.setTipoAtributo("lista de tipos MIME para subir ficheros");
		at.setIdAtributo(4);
		at.setNombre("accesskey");
		at.setTipoAtributo("lista de tipos MIME para subir fichero");
		at.setIdAtributo(5);
		at.setNombre("action");
		at.setTipoAtributo("procesador de formulario en servidor");
		at.setIdAtributo(6);
		at.setNombre("align");
		at.setTipoAtributo("título de una tabla/alineacion");
		at.setIdAtributo(7);
		at.setNombre("alink");
		at.setTipoAtributo("color de vínculos seleccionados");
		at.setIdAtributo(8);
		at.setNombre("alt");
		at.setTipoAtributo("descripción corta");
		at.setIdAtributo(9);
		at.setNombre("archive");
		at.setTipoAtributo("lista de archivos separados por comas");
		at.setIdAtributo(10);
		at.setNombre("axis");
		at.setTipoAtributo("lista de cabeceras relacionadas separadas por comas");
		at.setIdAtributo(11);
		at.setNombre("background");
		at.setTipoAtributo("fichero de textura de fondo del documento");
		at.setIdAtributo(12);
		at.setNombre("bgcolor");
		at.setTipoAtributo("color de fondo");
		at.setIdAtributo(13);
		at.setNombre("border");
		at.setTipoAtributo("Ancho y tipo de borde");
		at.setIdAtributo(14);
		at.setNombre("cellpadding");
		at.setTipoAtributo("espacio dentro de celdas");
		at.setIdAtributo(15);
		at.setNombre("char");
		at.setTipoAtributo("carácter de alineación");
		at.setIdAtributo(16);
		at.setNombre("charoff");
		at.setTipoAtributo("offset para carácter de alineación");
		at.setIdAtributo(17);
		at.setNombre("charset");
		at.setTipoAtributo("codificación de caracteres del recurso vinculado");
		at.setIdAtributo(18);
		at.setNombre("checked");
		at.setTipoAtributo("para radiobotones y casillas de verificación");
		at.setIdAtributo(19);
		at.setNombre("cite");
		at.setTipoAtributo("para radiobotones y casillas de verificación/informacion sobre razón de cambio");
		at.setIdAtributo(20);
		at.setNombre("class");
		at.setTipoAtributo("lista de clases separadas por espacios");
		at.setIdAtributo(21);
		at.setNombre("classid");
		at.setTipoAtributo("lista de clases separadas por espacios");
		at.setIdAtributo(22);
		at.setNombre("clear");
		at.setTipoAtributo("control del flujo de texto");
		at.setIdAtributo(23);
		at.setNombre("code");
		at.setTipoAtributo("fichero de clase applet");
		at.setIdAtributo(24);
		at.setNombre("codebase");
		at.setTipoAtributo("fichero de clase applet/URI base opcional para applet");
		at.setIdAtributo(25);
		at.setNombre("codetype");
		at.setTipoAtributo("tipo de contenido para code");
		at.setIdAtributo(26);
		at.setNombre("color");
		at.setTipoAtributo("color del texto");
		at.setIdAtributo(27);
		at.setNombre("cols");
		at.setTipoAtributo("lista de longitudes, por defecto: 100% (1 col)");
		at.setIdAtributo(28);
		at.setNombre("colspan");
		at.setTipoAtributo("número de columnas abarcado por celda");
		at.setIdAtributo(29);
		at.setNombre("compact");
		at.setTipoAtributo("espacio reducido entre objetos");
		at.setIdAtributo(30);
		at.setNombre("content");
		at.setTipoAtributo("información asociada");
		at.setIdAtributo(31);
		at.setNombre("coords");
		at.setTipoAtributo("lista de longitudes separadas por coma/para usar con mapas de imágenes en el cliente");
		at.setIdAtributo(32);
		at.setNombre("data");
		at.setTipoAtributo("referencia a datos del objeto");
		at.setIdAtributo(33);
		at.setNombre("datatime");
		at.setTipoAtributo("fecha y hora del cambio");
		at.setIdAtributo(34);
		at.setNombre("declare");
		at.setTipoAtributo("declara el objeto pero no lo crea");
		at.setIdAtributo(35);
		at.setNombre("defer");
		at.setTipoAtributo("El AU puede retrasar la ejecución del script");
		at.setIdAtributo(36);
		at.setNombre("dir");
		at.setTipoAtributo("dirección de texto débil/neutral");
		at.setIdAtributo(37);
		at.setNombre("disabled");
		at.setTipoAtributo("no disponible en este contexto");
		at.setIdAtributo(38);
		at.setNombre("enctype");
		at.setTipoAtributo("no disponible en este context");
		at.setIdAtributo(39);
		at.setNombre("face");
		at.setTipoAtributo("lista de nombres de fuentes separados por coma");
		at.setIdAtributo(40);
		at.setNombre("for");
		at.setTipoAtributo("empareja según valor de campo ID");
		at.setIdAtributo(41);
		at.setNombre("frame");
		at.setTipoAtributo("qué partes del marco representar");
		at.setIdAtributo(42);
		at.setNombre("frameborder");
		at.setTipoAtributo("pintar bordes del marco");
		at.setIdAtributo(43);
		at.setNombre("headers");
		at.setTipoAtributo("lista de id's de celdas de encabezado");
		at.setIdAtributo(44);
		at.setNombre("height");
		at.setTipoAtributo("altura de un elemento");
		at.setIdAtributo(45);
		at.setNombre("href");
		at.setTipoAtributo("URI del recurso vinculado");
		at.setIdAtributo(46);
		at.setNombre("hreflang");
		at.setTipoAtributo("código de idioma");
		at.setIdAtributo(47);
		at.setNombre("hspace");
		at.setTipoAtributo("espacio de relleno horizontal");
		at.setIdAtributo(48);
		at.setNombre("http-equiv");
		at.setTipoAtributo("nombre de encabezado HTTP de respuesta");
		at.setIdAtributo(49);
		at.setNombre("id");
		at.setTipoAtributo("id único en todo el documento");
		at.setIdAtributo(50);
		at.setNombre("ismp");
		at.setTipoAtributo("usar mapa de imágenes en servidor");
		at.setIdAtributo(51);
		at.setNombre("label");
		at.setTipoAtributo("para usar en menúes jerárquicos");
		at.setIdAtributo(52);
		at.setNombre("lang");
		at.setTipoAtributo("código de idioma");
		at.setIdAtributo(53);
		at.setNombre("lenguage");
		at.setTipoAtributo("nombre del lenguaje predefinido de scripts");
		at.setIdAtributo(54);
		at.setNombre("link");
		at.setTipoAtributo("color de los vínculos");
		at.setIdAtributo(55);
		at.setNombre("longdesc");
		at.setTipoAtributo("vínculo a descripción larga (complementa a alt)");
		at.setIdAtributo(56);
		at.setNombre("marginheight");
		at.setTipoAtributo("altura del margen en píxeles");
		at.setIdAtributo(57);
		at.setNombre("maxlegth");
		at.setTipoAtributo("anchura del margen en píxeles");
		at.setIdAtributo(58);
		at.setNombre("media");
		at.setTipoAtributo("diseñado para usar con estos medios");
		at.setIdAtributo(59);
		at.setNombre("method");
		at.setTipoAtributo("método HTTP usado para enviar el formulario");
		at.setIdAtributo(60);
		at.setNombre("multiple");
		at.setTipoAtributo("por defecto es selección simple");
		at.setIdAtributo(61);
		at.setNombre("name");
		at.setTipoAtributo("Nombre de un elemento/permite a los applets encontrarse entre sí");
		at.setIdAtributo(62);
		at.setNombre("nohref");
		at.setTipoAtributo("región sin acción");
		at.setIdAtributo(63);
		at.setNombre("noresize");
		at.setTipoAtributo("permitir a los usuarios redimensionar marcos");
		at.setIdAtributo(64);
		at.setNombre("noshade");
		at.setTipoAtributo("Define el aspecto");
		at.setIdAtributo(65);
		at.setNombre("nowrap");
		at.setTipoAtributo("suprimir ajuste automático de líneas");
		at.setIdAtributo(66);
		at.setNombre("object");
		at.setTipoAtributo("fichero applet serializado");
		at.setIdAtributo(67);
		at.setNombre("onblur");
		at.setTipoAtributo("el elemento perdió el foco");
		at.setIdAtributo(68);
		at.setNombre("onchange");
		at.setTipoAtributo("el valor del elemento fue modificado");
		at.setIdAtributo(69);
		at.setNombre("onclick");
		at.setTipoAtributo("se hizo clic con un botón del apuntador");
		at.setIdAtributo(70);
		at.setNombre("ondblclick");
		at.setTipoAtributo("se hizo doble clic con un botón del apuntador");
		at.setIdAtributo(71);
		at.setNombre("onfocus");
		at.setTipoAtributo("el foco se dirigió hacia el elemento");
		at.setIdAtributo(72);
		at.setNombre("onkeydown");
		at.setTipoAtributo("se pulsó una tecla");
		at.setIdAtributo(73);
		at.setNombre("onkeypress");
		at.setTipoAtributo("una tecla fue pulsada y soltada");
		at.setIdAtributo(74);
		at.setNombre("onkeyup");
		at.setTipoAtributo("una tecla fue soltada");
		at.setIdAtributo(75);
		at.setNombre("onload");
		at.setTipoAtributo("todos los marcos fueron cargados");
		at.setIdAtributo(76);
		at.setNombre("onmousedown");
		at.setTipoAtributo("se pulsó un botón del apuntador");
		at.setIdAtributo(77);
		at.setNombre("onmousemove");
		at.setTipoAtributo("se pulsó un botón del apuntador");
		at.setIdAtributo(78);
		at.setNombre("onmouseout");
		at.setTipoAtributo("un apuntador se quitó de encima del elemento");
		at.setIdAtributo(79);
		at.setNombre("onmouseover");
		at.setTipoAtributo("un apuntador se movió encima del elemento");
		at.setIdAtributo(80);
		at.setNombre("onmouseip");
		at.setTipoAtributo("se soltó un botón de un apuntador");
		at.setIdAtributo(81);
		at.setNombre("onreset");
		at.setTipoAtributo("el formulario fue reinicializado");
		at.setIdAtributo(82);
		at.setNombre("onselect");
		at.setTipoAtributo("se seleccionó parte de un texto");
		at.setIdAtributo(83);
		at.setNombre("onsubmit");
		at.setTipoAtributo("Formulario Enviado");
		at.setIdAtributo(84);
		at.setNombre("onunload");
		at.setTipoAtributo("Se quitaron todos los marcos");
		at.setIdAtributo(85);
		at.setNombre("profile");
		at.setTipoAtributo("Diccionario con numbres de metainformacion");
		at.setIdAtributo(86);
		at.setNombre("prompt");
		at.setTipoAtributo("mensaje indicador");
		at.setIdAtributo(87);
		at.setNombre("readonly");
		at.setTipoAtributo("texto y contraseñas");
		at.setIdAtributo(88);
		at.setNombre("rel");
		at.setTipoAtributo("tipos de vinculos directos");
		at.setIdAtributo(89);
		at.setNombre("rev");
		at.setTipoAtributo("tipos de vinculos inversos");
		at.setIdAtributo(90);
		at.setNombre("rows");
		at.setTipoAtributo("lista de longitudes por defecto");
		at.setIdAtributo(91);
		at.setNombre("rowspan");
		at.setTipoAtributo("número de filas abarcado por la celda");
		at.setIdAtributo(92);
		at.setNombre("rules");
		at.setTipoAtributo("línea de división entre filas y columnas");
		at.setIdAtributo(93);
		at.setNombre("scheme");
		at.setTipoAtributo("seleccionar forma de contenido");
		at.setIdAtributo(94);
		at.setNombre("scope");
		at.setTipoAtributo("campo de aplicación de una celda de cabecera");
		at.setIdAtributo(95);
		at.setNombre("scrolling");
		at.setTipoAtributo("barra de desplazamiento o no");
		at.setIdAtributo(96);
		at.setNombre("selected");
		at.setTipoAtributo("Indica que el elemento aparecerá seleccionado.");
		at.setIdAtributo(97);
		at.setNombre("shape");
		at.setTipoAtributo("controla la interpretación de las coordenadas");
		at.setIdAtributo(98);
		at.setNombre("size");
		at.setTipoAtributo("tamaño epefifico para un elemento");
		at.setIdAtributo(99);
		at.setNombre("span");
		at.setTipoAtributo("número de columnas por defecto en el grupo");
		at.setIdAtributo(100);
		at.setNombre("src");
		at.setTipoAtributo("URI del script externo");
		at.setIdAtributo(101);
		at.setNombre("standby");
		at.setTipoAtributo("mensaje a mostrar mientras se carga");
		at.setIdAtributo(102);
		at.setNombre("start");
		at.setTipoAtributo("número inicial de la secuencia");
		at.setIdAtributo(103);
		at.setNombre("style");
		at.setTipoAtributo("número inicial de la secuencia");
		at.setIdAtributo(104);
		at.setNombre("summary");
		at.setTipoAtributo("propósito/estructura para salida por voz");
		at.setIdAtributo(105);
		at.setNombre("tabindex");
		at.setTipoAtributo("posición en el orden de tabulación");
		at.setIdAtributo(106);
		at.setNombre("target");
		at.setTipoAtributo("representar en este marco");
		at.setIdAtributo(107);
		at.setNombre("text");
		at.setTipoAtributo("Color del texto en un documento");
		at.setIdAtributo(108);
		at.setNombre("title");
		at.setTipoAtributo("texto consultivo");
		at.setIdAtributo(109);
		at.setNombre("type");
		at.setTipoAtributo("tipo de contenido consultivo");
		at.setIdAtributo(110);
		at.setNombre("usemap");
		at.setTipoAtributo("usar mapa de imagenes del cluente");
		at.setIdAtributo(111);
		at.setNombre("valing");
		at.setTipoAtributo("alineacion vertical en celdas");
		at.setIdAtributo(112);
		at.setNombre("value");
		at.setTipoAtributo("valor de propiedad asociada");
		at.setIdAtributo(113);
		at.setNombre("valuetype");
		at.setTipoAtributo("Interpretacion del valor ");
		at.setIdAtributo(114);
		at.setNombre("version");
		at.setTipoAtributo("costante");
		at.setIdAtributo(115);
		at.setNombre("vlink");
		at.setTipoAtributo("color de los vinculos visitados");
		at.setIdAtributo(116);
		at.setNombre("vspace");
		at.setTipoAtributo("espacio vertical");
		at.setIdAtributo(117);
		at.setNombre("width");
		at.setTipoAtributo("anchura de un marco o elemento");
		at.setIdAtributo(118);
		at.setNombre("maxlength");
		at.setTipoAtributo("máximo de caracteres para campos de texto");	
	
		return at;
	}
	
	public Atributos addAtributos(int id, String nombre, String tipoEtiqueta){
		Atributos at = new Atributos(id, nombre, tipoEtiqueta);
		return at;
	}
	
	
	public List<Atributos> MuestraAtributos(){

		List<Atributos> listAt = new ArrayList<Atributos>();
		listAt.add(añadirAtributos());
		for(Atributos atr: listAt){
			System.out.println(at.getIdAtributo());
			System.out.println(at.getNombre());
			System.out.println(listAt.size());
		}
		return listAt;
	}*/

}
